// * PRIMO ESERICIO //
// ! PER PRIMA COSA CHIEDIAMO ALL'UTENTE UNA EMAIL DA INSERIRE
// ! DOPODICHE' CONTROLLIAMO SE TALE E-MAIL SIA PRESENTE NELL'ARRAY DI CUI IL PROGRAMMA E' FORNITO
// ! IN BASE AL FATTO CHE TROVI O NO UN ELEMENTO DELL ARRAY CHE VI CORRISPONDE MANDERMO IN OUTPUT
// ! L' ESITO PER LA RICHIESTA DEL UTENTE DI ENTRARE 